# Generated by Django 2.1.5 on 2019-09-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.CharField(choices=[('Coordinator', 'Coordinator'), ('Tasker', 'Tasker')], max_length=15),
        ),
    ]
