# Generated by Django 2.1.5 on 2019-09-18 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190917_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('assigned_by', models.CharField(max_length=200)),
                ('assigned_to', models.CharField(max_length=200)),
                ('assigned_date', models.DateField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=50)),
            ],
        ),
    ]
